### ISSUE TITLE
NSDI '21 | Tegra: Efficient Ad-Hoc Analytics on Evolving Graphs

### ISSUE THREAD

**Issue by yuchenzhong** [yuchenzhong/read-papers#265]
https://www.usenix.org/system/files/nsdi21-iyer.pdf

**Comment by yuchenzhong** [comment]
https://docs.google.com/presentation/d/1WfOXESa_34Fkowv6VSTW3q1UsIXOGe7YnituLcbPP1E/edit?usp=sharing

**Comment by jasperzhong** [comment]
我的理解是，可以retrieve任意时间的一个snapshot，然后再在上面做graph processing，like k-hop.
