### ISSUE TITLE
ICLR '19 | How Powerful are Graph Neural Networks?

### ISSUE THREAD

**Issue by yuchenzhong** [yuchenzhong/read-papers#271]
https://arxiv.org/pdf/1810.00826

**Comment by yuchenzhong** [comment]
https://zhuanlan.zhihu.com/p/66589334

直接看这个讲解吧. 我看不懂原文...too theoretical. 

GIN
![image](https://user-images.githubusercontent.com/25879526/157033701-76bfbf94-4e9b-48dc-a9ea-21e7dae94498.png)

**Comment by jasperzhong** [comment]
https://docs.dgl.ai/en/latest/_modules/dgl/nn/pytorch/conv/ginconv.html#GINConv

看代码更帮助理解.
