### ISSUE TITLE
arXiv '19 | Deep Graph Library: A Graph-Centric, Highly-Performant Package for Graph Neural Networks

### ISSUE THREAD

**Issue by yuchenzhong** [yuchenzhong/read-papers#282]
https://arxiv.org/pdf/1909.01315

**Comment by yuchenzhong** [comment]
GNN可以总结为: 

![image](https://user-images.githubusercontent.com/25879526/158326575-4ac0c8db-63fd-4050-af58-5a6fc73a58c9.png)

- φ: message function. generate a message by combining the edge feature with the features of incident nodes. 
- ψ: update function. update each node feature.
- ρ: reduce function.  aggregate its incoming messages. e.g., max/min/mean, or LSTM #278 .


BTW, what is `incident nodes`? See http://stackoverflow.com/questions/16885897/ddg#16886038

**Comment by yuchenzhong** [comment]
实现GNN最关键的是message passing如何实现. DGL把message passing抽象成sparse matrix operations. 

主要有两种操作:
- **Sparse-dense matrix multiplication (SpMM)**: Y = AX 比如GCN #128 
- **Sampled dense-dense matrix multiplication (SDDMM)**: W = A (XX^T) 比如GAT #266

**Comment by yuchenzhong** [comment]
后面比较了node parallel和edge parallel两种并行方式. 

![image](https://user-images.githubusercontent.com/25879526/158368532-19bd611f-880a-4c6e-8027-3ef837212b7f.png)


啥？每个node/edge开一个线程？这里应该是说一个node/edge由一个thread控制吧... 

__

关于Compressed sparse row (CSR)和Coordinate list (COO)

- CSR: 分成两部分: non-zero values列表，和对应的indices列表
- COO: list of (index, value)

https://en.wikipedia.org/wiki/Sparse_matrix

**Comment by yuchenzhong** [comment]
后面还提到了通过调用g.update_all(φ, ρ) 来invoke g-SpMM和g-SDDMM. 并且可以让用户指定φ和ρ. DGL提供了最常用的φ和ρ并且为每一个组合生成了kernel. wow. 然后还提到了一些优化.

**Comment by yuchenzhong** [comment]
实验略.

**Comment by jasperzhong** [comment]
g.update_all()调用的是SpMM，做aggregation; g.apply_edges()是调用SDDMM.
